import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const readDesktopFile = (name: string) =>
  readFileSync(new URL(`./${name}`, import.meta.url), 'utf8')

describe('desktop surface contract', () => {
  it('keeps the Electron boundary isolated', () => {
    const main = readDesktopFile('main.mjs')

    expect(main).toContain('contextIsolation: true')
    expect(main).toContain('nodeIntegration: false')
    expect(main).toContain('sandbox: true')
    expect(main).toContain("mainWindow.webContents.on('will-navigate'")
    expect(main).toContain("mainWindow.webContents.on('will-redirect'")
    expect(main).toContain("mainWindow.webContents.on('will-attach-webview'")
    expect(main).toContain('mainWindow.webContents.setWindowOpenHandler')
    expect(main).toContain('mainWindow.webContents.session.setPermissionRequestHandler')
    expect(main).toContain('assertTrustedIpcSender(event)')
    expect(main).toContain("event.sender !== mainWindow.webContents")
    expect(main).toContain("actual.protocol === 'file:' && fileURLToPath(actual) === rendererEntryPath")
    expect(main).not.toContain('requireProductAccess: true')
    expect(main).toContain('assertRuntimeResetAllowed()')
    expect(main).toContain('runtimeHost.transitionBlocker()')
    expect(main).not.toContain('externalTransitionBlocker:')
    expect(main).toContain("label: '文件'")
    expect(main).toContain("label: '新建对话', accelerator: 'CmdOrCtrl+N'")
    expect(main).toContain("label: '打开文件夹…', accelerator: 'CmdOrCtrl+O'")
    expect(main).toContain("role: 'close', label: '关闭窗口'")
    expect(main).toContain("unscopedWorkspacePath: unscopedWorkspacePath()")
    expect(main).toContain('const browserSystems = new Map()')
    expect(main).toContain('const computerSystems = new Map()')
    expect(main).toContain('systems.browser.register(client)')
    expect(main).toContain('systems.computer.register(client)')
    expect(main).toContain('browserSystems.get(conversationId)?.pauseForRuntime()')
    expect(main).toContain('computerSystems.get(conversationId)?.pauseForRuntime()')
    expect(main).toContain('computerLeaseOwnerId')
    expect(main).toContain("mainWindow.webContents.send('desktop:runtime-event', event)")
    expect(main).not.toContain("window.webContents.send('desktop:runtime-event', event)")
  })

  it('exposes only the intended preload operations', () => {
    const preload = readDesktopFile('preload.cjs')

    expect(preload).toContain("getSnapshot: () => ipcRenderer.invoke('desktop:get-snapshot')")
    expect(preload).toContain("getSettings: forceModels => ipcRenderer.invoke('desktop:get-settings', forceModels)")
    expect(preload).toContain("saveSettings: update => ipcRenderer.invoke('desktop:save-settings', update)")
    expect(preload).toContain("listCommands: () => ipcRenderer.invoke('desktop:list-commands')")
    expect(preload).toContain("listSkillMarketplace: () => ipcRenderer.invoke('desktop:list-skill-marketplace')")
    expect(preload).toContain("installMarketplaceSkill: (marketplaceId, allowOverwrite) => ipcRenderer.invoke('desktop:install-marketplace-skill', marketplaceId, allowOverwrite)")
    expect(preload).toContain("uninstallMarketplaceSkill: marketplaceId => ipcRenderer.invoke('desktop:uninstall-marketplace-skill', marketplaceId)")
    expect(preload).toContain("listWorkPacks: () => ipcRenderer.invoke('desktop:list-work-packs')")
    expect(preload).toContain("installWorkPack: (workPackId, allowOverwrite) => ipcRenderer.invoke('desktop:install-work-pack', workPackId, allowOverwrite)")
    expect(preload).toContain("setWorkPackEnabled: (workPackId, enabled) => ipcRenderer.invoke('desktop:set-work-pack-enabled', workPackId, enabled)")
    expect(preload).toContain("uninstallWorkPack: workPackId => ipcRenderer.invoke('desktop:uninstall-work-pack', workPackId)")
    expect(preload).toContain("executeCommand: command => ipcRenderer.invoke('desktop:execute-command', command)")
    expect(preload).toContain("submitPrompt: (prompt, attachments, capabilities) => ipcRenderer.invoke('desktop:submit-prompt', prompt, attachments, capabilities)")
    expect(preload).toContain("resendFromTurn: (turnId, prompt) => ipcRenderer.invoke('desktop:resend-from-turn', turnId, prompt)")
    expect(preload).not.toContain('desktop:list-terminals')
    expect(preload).not.toContain('desktop:create-terminal')
    expect(preload).not.toContain('desktop:read-terminal')
    expect(preload).not.toContain('desktop:write-terminal')
    expect(preload).toContain("openExternal: url => ipcRenderer.invoke('desktop:open-external', url)")
    expect(preload).toContain("browserShow: () => ipcRenderer.invoke('desktop:browser-show')")
    expect(preload).toContain("browserSetBounds: bounds => ipcRenderer.invoke('desktop:browser-set-bounds', bounds)")
    expect(preload).toContain("ipcRenderer.on('desktop:browser-event', handler)")
    expect(preload).toContain("stop: () => ipcRenderer.invoke('desktop:stop')")
    expect(preload).toContain("resolveRequest: (requestId, response) => ipcRenderer.invoke('desktop:resolve-request', requestId, response)")
    expect(preload).toContain("newConversation: () => ipcRenderer.invoke('desktop:new-conversation')")
    expect(preload).toContain("newConversationInProject: id => ipcRenderer.invoke('desktop:new-project-conversation', id)")
    expect(preload).toContain("renameConversation: (id, title) => ipcRenderer.invoke('desktop:rename-conversation', id, title)")
    expect(preload).toContain("readSubAgent: (taskId, offset, limit) => ipcRenderer.invoke('desktop:read-subagent', taskId, offset, limit)")
    expect(preload).toContain("stopSubAgent: taskId => ipcRenderer.invoke('desktop:stop-subagent', taskId)")
    expect(preload).toContain("retrySubAgent: taskId => ipcRenderer.invoke('desktop:retry-subagent', taskId)")
    expect(preload).toContain("controlWorkStep: (taskId, action) => ipcRenderer.invoke('desktop:control-work-step', taskId, action)")
    expect(preload).toContain("gitStage: paths => ipcRenderer.invoke('desktop:git-stage', paths)")
    expect(preload).toContain("gitUnstage: paths => ipcRenderer.invoke('desktop:git-unstage', paths)")
    expect(preload).toContain("gitCommit: (message, paths) => ipcRenderer.invoke('desktop:git-commit', message, paths)")
    expect(preload).toContain("gitPush: (remote, branch, setUpstream) => ipcRenderer.invoke('desktop:git-push', remote, branch, setUpstream)")
    expect(preload).toContain("runAutomation: id => ipcRenderer.invoke('desktop:run-automation', id)")
    expect(preload).toContain("retryAutomationRun: (id, runId) => ipcRenderer.invoke('desktop:retry-automation-run', id, runId)")
    expect(preload).toContain("cancelAutomationRun: id => ipcRenderer.invoke('desktop:cancel-automation-run', id)")
    expect(preload).toContain("importFiles: paths => ipcRenderer.invoke('desktop:import-files', paths)")
    expect(preload).toContain("importClipboardImage: (base64, mime, filename) => ipcRenderer.invoke('desktop:import-clipboard-image', base64, mime, filename)")
    expect(preload).toContain("previewArtifact: (id, purpose = 'full') => ipcRenderer.invoke('desktop:preview-artifact', id, purpose)")
    expect(preload).toContain("previewImageAttachment: (path, purpose = 'full') => ipcRenderer.invoke('desktop:preview-image-attachment', path, purpose)")
    expect(preload).toContain("exportImageAttachment: path => ipcRenderer.invoke('desktop:export-image-attachment', path)")
    expect(preload).toContain("installPlugin: () => ipcRenderer.invoke('desktop:install-plugin')")
    expect(preload).toContain("setPluginEnabled: (id, enabled) => ipcRenderer.invoke('desktop:set-plugin-enabled', id, enabled)")
    expect(preload).toContain("chooseWorkspace: () => ipcRenderer.invoke('desktop:choose-workspace')")
    expect(preload).toContain("ipcRenderer.on('desktop:runtime-event', handler)")
    expect(preload).not.toContain('ipcRenderer.send(')
  })

  it('provides desktop-native composer and settings interactions', () => {
    const rendererEntry = readDesktopFile('renderer/main.ts')
    const renderer = readDesktopFile('renderer/workbench.ts')
    const linearTaskFlow = readDesktopFile('renderer/linearTaskFlow.ts')
    const imageLightbox = readDesktopFile('renderer/imageLightbox.ts')
    const visualEvidence = readDesktopFile('renderer/visualEvidence.ts')
    const settings = readDesktopFile('renderer/settingsCenter.ts')
    const computer = readDesktopFile('renderer/computerControls.ts')
    const styles = readDesktopFile('renderer/styles.css')

    expect(renderer).toContain("event.key === 'Enter' && !event.shiftKey && !event.isComposing")
    expect(renderer).toContain('M21 3 10.6 13.4')
    expect(renderer).not.toContain('id="terminal-toggle"')
    expect(renderer).not.toContain('id="terminal-panel"')
    expect(renderer).not.toContain('id="runtime-toggle"')
    expect(renderer).not.toContain("event.key.toLowerCase() === 'j'")
    expect(renderer).toContain("createSettingsCenter(app, bridge")
    expect(renderer).not.toContain("createAccountCenter(app, bridge")
    expect(settings).not.toContain('TurboFlux 官方托管模型与自己的 API 可以同时保留')
    expect(styles).toContain('.markdown-body ol { padding-left: 2.45em; }')
    expect(styles).toContain('--content-block-gap: 8px')
    expect(styles).toContain('--flow-row-height: 25px')
    expect(styles).toContain('.linear-task-flow > .linear-flow-item[data-flow-gap="content"] { margin-top: var(--content-block-gap); }')
    expect(styles).toContain('.linear-task-flow .message-row.assistant .markdown-body > * { margin-top: 0; margin-bottom: 0; }')
    expect(styles).toContain('.linear-disclosure:not(.expanded) > .linear-disclosure-body > .linear-disclosure-body-inner')
    expect(styles).toContain('.linear-task-flow .message-row.assistant .markdown-body code:not(pre code) { padding-top: 0; padding-bottom: 0;')
    expect(styles).toContain('.execution-group .tool-activity { position: relative; margin: 0 0 var(--content-block-gap);')
    expect(renderer).toContain('renderedConversationSignature')
    expect(renderer).toContain('function handleConversationEvent(event: AnyConversationEvent)')
    expect(renderer).toContain('const turn = event.payload.turn')
    const canonicalHandler = renderer.slice(
      renderer.indexOf('function handleConversationEvent(event: AnyConversationEvent)'),
      renderer.indexOf('function handleRuntimeEvent(event: WorkbenchEvent)'),
    )
    expect(canonicalHandler).not.toContain('appendTurn(')
    expect(canonicalHandler).not.toContain('appendStream(')
    expect(canonicalHandler).not.toContain('appendThinking(')
    expect(canonicalHandler).not.toContain('startStream(')
    expect(canonicalHandler).not.toContain('finishStreams(')
    expect(renderer).not.toContain('startRequestStatus(')
    expect(renderer).not.toContain('request-progress')
    expect(renderer).not.toContain('assistant-signature')
    expect(renderer).toContain('hasRenderableTurnPayload({')
    expect(renderer).toContain('createLinearTaskFlowRenderer(transcript, {')
    expect(renderer).toContain('renderCanonicalTaskFlow(true)')
    expect(renderer).not.toContain("round.className = 'execution-round'")
    expect(renderer).not.toContain('继续处理')
    expect(renderer).not.toContain('function startStream()')
    expect(renderer).not.toContain('function appendStream(')
    expect(renderer).not.toContain('function appendThinking(')
    expect(renderer).not.toContain('liveToolRounds')
    expect(renderer).toContain('resolveTool: node => {')
    expect(renderer).not.toContain('if (!activeTurnIsTask) return')
    expect(renderer).not.toContain("thinkingElement.dataset.userExpanded = 'false'")
    expect(renderer).not.toContain("block.dataset.userExpanded = 'false'")
    expect(renderer).not.toContain('function appendExecutionTurn(')
    expect(renderer).not.toContain('adoptLiveExecutionContent(')
    expect(renderer).not.toContain('applyExecutionStepVisibility(')
    expect(renderer).not.toContain('shouldFinalizeAssistantTurnInTask(')
    expect(renderer).toContain("case 'run.completed':")
    expect(renderer).toContain('refreshConversationSystemSnapshots()')
    expect(renderer).toContain("event.type === 'conversation-run'")
    expect(renderer).toContain("event.type === 'conversation-event'")
    expect(renderer).not.toContain("event.type === 'flow-event'")
    expect(renderer).not.toContain("event.type === 'work-event'")
    expect(renderer).not.toContain("event.type === 'agent'")
    expect(renderer).toContain('applyTaskFlowEvent(taskFlowProjection, event.event)')
    expect(renderer).toContain('canonicalTaskFlowFrame = window.requestAnimationFrame')
    expect(renderer).toContain('liveTurnCache.set(turn.id, turn)')
    expect(renderer).toContain("element.classList.add('optimistic-user-turn')")
    expect(renderer).toContain('reconcileOptimisticUserTurn(turn)')
    expect(renderer).toContain('scheduleCanonicalTaskFlowRender()')
    expect(renderer).toContain('applyTaskFlowEvent(taskFlowProjection, event.event)')
    expect(renderer).toContain('showToast(`${title} 已完成`)')
    expect(renderer).not.toContain('createTaskDurationLabel')
    expect(renderer).toContain('snapshotRefreshInFlight')
    expect(renderer).toContain('createCommandPalette(app, bridge')
    expect(renderer).toContain("createWorkOverviewSection('工作面')")
    expect(renderer).toContain("createWorkOverviewSection('浏览现场'")
    expect(renderer).toContain("createWorkOverviewSection('协作现场')")
    expect(renderer).toContain("createWorkOverviewSection('交付记录'")
    expect(renderer).toContain("'danger-full-access': '完整访问'")
    expect(renderer).not.toContain('任务、Agent 与 Flow')
    expect(renderer).toContain("value.startsWith('/')")
    expect(renderer).not.toContain('id="mode-switch"')
    expect(renderer).toContain('id="composer-add"')
    expect(renderer).toContain('class="sidebar-nav-item work-packs-entry" data-view="skills"')
    expect(renderer).toContain('id="settings-button" title="设置"')
    expect(renderer).not.toContain('id="workspace-picker"')
    expect(renderer).not.toContain('<small>当前工作区</small>')
    expect(renderer).toContain('id="composer-start-workspace-name">选择工作区</span>')
    expect(renderer).not.toContain('avatar.textContent = displayName.slice(0, 1)')
    expect(renderer).not.toContain("querySelector<HTMLElement>('#sidebar-panel-avatar')!.textContent")
    expect(renderer).toContain('class="workbench-prompt-title" aria-label="TurboFlux Work 与 TurboFlux Code"')
    expect(renderer).toContain('<span class="workbench-title-brand">TurboFlux</span>')
    expect(renderer).toContain("{ word: 'Work', className: 'is-work' }")
    expect(renderer).toContain("{ word: 'Code', className: 'is-code' }")
    expect(renderer).toContain('const PRODUCT_TITLE_TYPE_DELAY = 120')
    expect(renderer).toContain('const PRODUCT_TITLE_DELETE_DELAY = 78')
    expect(renderer).toContain('const PRODUCT_TITLE_HOLD_DELAY = 1550')
    expect(renderer).toContain('const PRODUCT_TITLE_SWITCH_DELAY = 260')
    expect(styles).toContain('.workbench-title-product.is-work { color: #f0522d; }')
    expect(styles).toContain('.workbench-title-product.is-code { color: #4d63f2; }')
    expect(styles).toContain('font-size: clamp(44px,5vw,72px)')
    expect(renderer).not.toContain('id="home-conversation-list"')
    expect(renderer).not.toContain('未命名任务')
    expect(renderer).toContain('Number.MAX_SAFE_INTEGER')
    expect(renderer).toContain('projectWorkspaceConversationGroups({')
    expect(renderer).toContain("workspaceGroupExpansionStorageKey = 'turboflux.workspace-groups.expansion'")
    expect(renderer).toContain('bridge.newConversationInProject(group.projectId!)')
    expect(renderer).not.toContain('今天想完成什么工作？')
    expect(styles).toContain('.workbench-prompt-title')
    expect(renderer).not.toContain('class="quick-card"')
    expect(renderer).not.toContain('composer-start-guidance')
    expect(renderer).not.toContain('研究资料并整理清晰结论')
    expect(renderer).not.toContain('class="composer-rail"')
    expect(renderer).toContain('id="browser-workspace"')
    expect(renderer).toContain('id="inspector-overview-back"')
    expect(renderer).toContain("type InspectorTab = 'overview' | 'activity' | 'outputs' | 'browser' | 'context' | 'git'")
    expect(renderer).toContain("type BrowserDisplayMode = 'workspace' | 'inspector' | null")
    expect(renderer).toContain("button.addEventListener('click', () => void openBrowserInInspector(view.previewUrl!))")
    expect(renderer).toContain('id="task-companion"')
    expect(renderer).toContain('id="work-plan-dock"')
    expect(renderer).toContain('id="inspector-toggle" title="打开工作侧栏">${icon(\'panel\')}</button>')
    expect(renderer).toContain("if (item.kind === 'preview' && preview?.url) void openBrowserInInspector(preview.url)")
    expect(renderer).toContain("if (item.kind === 'browser' && browser?.tabId) void openBrowserTabInInspector(browser.tabId)")
    expect(renderer).toContain('onOpenBrowser: isBuiltInBrowserTool(call.name)')
    expect(renderer).toContain('function openBrowserExecution(toolCallId: string)')
    expect(linearTaskFlow).toContain('onOpenBrowser?: () => void')
    expect(linearTaskFlow).toContain('tool.onOpenBrowser?.()')
    expect(linearTaskFlow).toContain('options.resolveTool(item.nodes.at(-1)!).onOpenBrowser?.()')
    const browserStateRenderer = renderer.slice(renderer.indexOf('function renderBrowserSnapshot'), renderer.indexOf('async function openBrowser()'))
    expect(browserStateRenderer).toContain("openInspector('browser')")
    expect(browserStateRenderer).toContain('agentToolCallId !== lastAutoOpenedBrowserToolCallId')
    expect(renderer).toContain('function updateInspectorBrowser(snapshot: BrowserSystemSnapshot): boolean')
    expect(browserStateRenderer).toContain("else if (currentInspectorTab === 'browser' && !updateInspectorBrowser(snapshot)) renderInspector()")
    expect(browserStateRenderer).not.toContain("currentInspectorTab === 'browser' && !inspectorAddressFocused")
    expect(renderer).toContain("renderBrowserTabs(tabs, true)")
    expect(renderer).toContain("addressForm.className = 'inspector-browser-address-form'")
    expect(renderer).toContain("newTab.addEventListener('click'")
    expect(renderer).toContain("event.metaKey && event.key.toLowerCase() === 't' && browserSnapshot?.visible")
    expect(renderer).toContain("inspectorContent.querySelector<HTMLInputElement>('.inspector-browser-address')")
    expect(renderer).not.toContain('Agent 浏览器')
    expect(renderer).toContain('bridge.browserSetBounds')
    expect(renderer).toContain('if (!rect || rect.width < 2 || rect.height < 2) return')
    expect(styles).toContain('.inspector-browser-surface')
    expect(styles).toContain('.inspector-browser-tabbar')
    expect(styles).toContain('.browser-activity-pill[hidden]')
    expect(renderer).toContain('id="approval-pill"')
    expect(renderer).toContain("appendComposerMenuSection('插件', capabilityMenu)")
    expect(renderer).toContain('Promise.all([bridge.listPlugins(), bridge.getSettings(false)])')
    expect(renderer).toContain('for (const plugin of registry.plugins)')
    expect(renderer).toContain('projectedCapabilityKeys.has(`mcp:${server.name}`)')
    expect(renderer).not.toContain('bridge.listWorkPacks()')
    expect(renderer).toContain("server.name === 'computer' ? icon('computer')")
    expect(renderer).toContain('const submittedCapabilities = draftCapabilities.length > 0')
    expect(renderer).toContain('submittedCapabilities,')
    expect(renderer).toContain('id="capability-name"')
    expect(renderer).toContain("capability.id === 'computer'")
    expect(renderer).toContain('本轮优先使用，点击管理')
    expect(renderer).toContain('未选择的插件和 Skills 仍然可用')
    expect(renderer).toContain('let pendingConversationRender = false')
    expect(renderer).toContain('if (editingTurnId && !conversationChanged)')
    expect(renderer).toContain('captureTranscriptViewportAnchor()')
    expect(renderer).toContain('const composerActionGuard = new SingleFlightGuard()')
    expect(renderer).toContain('const resendGuard = new SingleFlightGuard()')
    expect(renderer).toContain('draftRecordQueue.enqueue(() => bridge.recordDraft(draft))')
    expect(renderer).toContain('composerActionGuard.active || conversationNavigationGuard.active')
    expect(renderer).toContain("dialog.setAttribute('aria-modal', 'true')")
    expect(renderer).toContain("transcriptMutationObserver.observe(transcript, { childList: true })")
    expect(renderer).not.toContain('subtree: true, characterData: true')
    expect(renderer).toContain("if (currentSnapshot?.runtime.status === 'running') await bridge.stop()")
    expect(renderer).toContain("'turboflux.inspector.width'")
    expect(renderer).toContain("inspectorResizeHandle.addEventListener('pointerdown'")
    expect(renderer).toContain("inspectorResizeHandle.addEventListener('keydown'")
    expect(renderer).toContain('inspectorWidthFromKey(')
    expect(renderer).toContain("aria-keyshortcuts=\"ArrowLeft ArrowRight Shift+ArrowLeft Shift+ArrowRight Home\"")
    expect(styles).toMatch(/\.inspector-resize-handle \{[^}]*width: 24px/)
    expect(styles).toContain('.inspector-resize-handle:focus-visible::after')
    expect(styles).toContain('scrollbar-gutter: stable')
    expect(styles).toContain('.desktop-shell.inspector-open .main-panel { margin-right: var(--work-panel-width); }')
    expect(styles).not.toContain('.desktop-shell.inspector-open .conversation-mode .transcript')
    expect(styles).toContain('.inspector { position: absolute; z-index: 150; top: 0; right: 0;')
    expect(styles).toContain('container-type: inline-size')
    expect(renderer).toContain('inspectorDismissTriggerX(')
    expect(renderer).toContain('shouldDismissInspectorAtPointer(')
    expect(renderer).toContain('closeInspector(true)')
    expect(renderer).toContain("window.addEventListener('pointerup', finish)")
    expect(styles).toContain('.linear-turn-status::after')
    expect(styles).not.toContain('.request-progress')
    expect(styles).not.toContain('.assistant-signature')
    expect(styles).toMatch(/\.image-lightbox \{[^}]*background: transparent;/)
    expect(styles).not.toContain('max-height: 1600px')
    expect(renderer).toContain('await persistDraftNow()')
    expect(settings).toContain("{ id: 'computer', title: '电脑操控'")
    expect(computer).toContain("button.textContent = '原生申请'")
    expect(computer).toContain("'开始原生引导'")
    expect(computer).toContain("'继续原生引导'")
    expect(computer).toContain("result.outcome === 'cancelled'")
    expect(renderer).toContain("event.clipboardData?.getData('text/plain')")
    expect(renderer).toContain('bridge.pathForFile(file)')
    expect(settings).toContain("bridge.getSettings(force)")
    expect(settings).toContain("bridge.saveSettings(draft)")
    expect(settings).toContain('已安全保存 · 留空保持不变')
    expect(settings).toContain("if (!entry.installed) return '立即安装'")
    expect(settings).toContain('skill-install-track')
    expect(settings).toContain('class="official-market"')
    expect(settings).toContain('class="official-pack-detail"')
    expect(settings).not.toContain('TurboFlux Official')
    expect(settings).not.toContain('<span>TurboFlux 官方能力</span>')
        expect(settings).not.toContain('整幅推荐图待接入')
    expect(settings).not.toContain('整幅产品展示图待接入')
    expect(settings).not.toContain('official-pack-showcase')
    expect(settings).toContain('official-pack-summary')
    expect(settings).toContain('official-pack-text-section')
    expect(settings).toContain("entry.icon === 'pdf-file'")
    expect(settings).toContain('official-pack-file-icon')
    expect(styles).toContain('.official-pack-file-icon')
    expect(settings).not.toContain('official-feature-art')
    expect(settings).not.toContain('official-pack-showcase-visual')
    const officialMarketStyles = styles.slice(styles.indexOf('.official-market, .official-pack-detail'), styles.indexOf('.command-palette-overlay'))
    expect(officialMarketStyles).not.toContain('linear-gradient')
    expect(officialMarketStyles).not.toContain('radial-gradient')
    expect(settings).toContain('搜索能力')
    expect(settings).not.toContain('查看来源 ↗')
    expect(settings).not.toContain('导入 SKILL.md')
    expect(settings).not.toContain('社区来源')
    expect(settings).not.toContain('Skills 目录')
    expect(settings).not.toContain('bridge.listSkillMarketplace()')
    expect(settings).not.toContain('bridge.installMarketplaceSkill(')
    expect(settings).not.toContain('bridge.uninstallMarketplaceSkill(')
    expect(renderer).not.toContain('onUseSkill: async skillId =>')
    expect(renderer).toContain('onUseCapability: async capability =>')
    expect(renderer).not.toContain('taskInput.value = promptTemplate')
    expect(settings).not.toContain('options.onUseSkill')
    const picker = settings.slice(settings.indexOf('async function openModelPicker'), settings.indexOf("overlay.querySelector('#settings-back')"))
    expect(picker).toContain('正在读取模型…')
    expect(picker.indexOf("popover.classList.add('visible')")).toBeLessThan(picker.indexOf('await ensureSettings()'))
    expect(picker).toContain("if (!popover.classList.contains('visible')) return")
    expect(settings).toContain("popover.classList.remove('submenu-left')")
    expect(settings).toContain('anchoredComposerPopoverPosition(')
    expect(settings).toContain("options.getComposerPopoverPlacement?.() || 'above'")
    expect(settings).toContain('popover.dataset.placement = position.placement')
    expect(settings).toContain("popover.className = 'model-popover model-only-popover'")
    expect(settings).toContain("popover.className = 'model-popover reasoning-popover'")
    expect(settings).toContain('id="reasoning-slider"')
    expect(settings).toContain('step="1"')
    expect(settings).toContain('class="reasoning-slider-thumb"')
    expect(settings).toContain('persistQuickChange({ keepPickerOpen: true, applySnapshot: false })')
    expect(settings).toContain("slider.addEventListener('input', () => {")
    expect(settings).not.toContain("slider.addEventListener('change'")
    expect(settings).toContain("slider.addEventListener('pointerdown', () => card.classList.add('is-dragging'))")
    expect(settings).toContain("slider.addEventListener('lostpointercapture', finishDragging)")
    expect(settings).toContain("reasoningName.textContent = option.label")
    expect(settings).toContain('latestReasoningIndex = index')
    expect(settings).toContain('reasoningRevision += 1')
    expect(settings).toContain('persistedReasoningRevision < reasoningRevision')
    expect(settings).toContain('pendingProfile.reasoning = { ...pendingOption.config }')
    expect(settings).toContain('let persistFailed = false')
    expect(settings).toContain('if (!persistFailed && persistedReasoningRevision < reasoningRevision)')
    expect(settings).toContain('applySnapshot: false')
    expect(settings).toContain('}, 80)')
    expect(settings).not.toContain('let commitQueue = Promise.resolve()')
    expect(settings).toContain('if (!behavior.keepPickerOpen) hidePicker()')
    expect(settings).toContain('const currentProfile = draft ? selectedProfile(draft) : undefined')
    expect(settings).toContain("mcpServers: undefined")
    expect(settings).toContain('filter(server => !server.system)')
    expect(settings).toContain('随 TurboFlux 桌面端提供，由核心维护')
    expect(settings).toContain('class="settings-window"')
    expect(settings).toContain('id="settings-search"')
    expect(settings).toContain('settingsNavigationMarkup()')
    expect(styles).toContain('grid-template-columns: 264px minmax(0, 1fr)')
    expect(styles).toContain('width: 100%; height: 100%')
    expect(styles).toContain('.capability-tab { width: auto; max-width: 168px; flex: 0 1 auto;')
    expect(styles).toContain('.capability-tab #capability-name')
    expect(styles).toContain('.computer-guide-action')
    expect(styles).toContain('.reasoning-tab { width: auto; max-width: 168px; flex: 0 1 auto;')
    expect(styles).toContain('[data-reasoning-tone="max"] { --reasoning-color: #1c1c1e;')
    expect(styles).toContain('height: 12px; overflow: hidden;')
    expect(styles).toContain('width: 28px; height: 28px;')
    expect(styles).toContain('.reasoning-slider-card.is-dragging')
    expect(styles).toContain('transform: translate(-50%,-50%) scale(1.055)')
    expect(styles).toContain('@keyframes reasoning-max-spectrum-sweep')
    expect(styles).not.toContain('@keyframes reasoning-liquid-flow')
    expect(renderer).toContain('bridge.readSubAgent(id, offset, limit)')
    expect(renderer).toContain('bridge.stopSubAgent(id)')
    expect(renderer).toContain('bridge.retrySubAgent(id)')
    expect(renderer).toContain('bridge.controlWorkStep(id, action)')
    expect(styles).toContain('.subagent-timeline-row')
    expect(renderer).toContain('bridge.gitStage(paths)')
    expect(renderer).toContain('bridge.gitRestore(paths)')
    expect(renderer).toContain('bridge.gitPush(remote, branch, setUpstream)')
    expect(renderer).toContain("bridge.previewArtifact(artifactId, 'thumbnail')")
    expect(renderer).toContain('bridge?.exportArtifact(artifact.id)')
    expect(renderer).toContain('refreshExecutionVisualEvidence(snapshot)')
    expect(renderer).toContain("host.className = 'execution-visual-evidence linear-flow-visual-evidence'")
    expect(styles).toContain('.visual-evidence-thumbnail')
    expect(styles).toContain('.image-lightbox')
    expect(styles).toContain('background: transparent')
    expect(styles).toContain('.draft-image-remove::before')
    expect(renderer).toContain("gallery.className = 'message-image-grid'")
    expect(renderer).toContain("card.className = 'draft-image-card'")
    expect(renderer).toContain('bridge.previewImageAttachment(path, purpose)')
    expect(imageLightbox).toContain("if (typeof image.decode === 'function') await image.decode()")
    expect(imageLightbox).not.toContain('for (const adjacent of')
    expect(visualEvidence).toContain('options.defaultCollapsed !== false')
    expect(visualEvidence).toContain('if (!collapsed) mountThumbnails()')
    expect(settings).toContain("{ id: 'workpacks', title: '插件'")
    expect(settings).toContain('bridge.listWorkPacks()')
    expect(settings).toContain('bridge.installWorkPack(id, overwrite)')
    expect(settings).toContain('bridge.setWorkPackEnabled(id, enabled)')
    expect(settings).toContain('bridge.uninstallWorkPack(id)')
    expect(settings).not.toContain('bridge.installMarketplacePlugin(')
    expect(settings).not.toContain('bridge.setPluginEnabled(')
    expect(styles).toContain('.git-inline-diff')
    const browser = readDesktopFile('browser/browserSystem.ts')
    const browserTools = readDesktopFile('browser/browserTools.ts')
    expect(browserTools).toContain("name: 'upload_file'")
    expect(browser).toContain("debuggerApi.sendCommand('DOM.setFileInputFiles'")
    expect(browser).toContain('Browser uploads must use a file inside the active workspace')
  })

  it('hosts the shared application runtime outside the renderer', () => {
    const main = readDesktopFile('main.mjs')
    const runtimeHost = readDesktopFile('runtimeHost.ts')

    expect(main).toContain("tsImport('./runtimeHost.ts', import.meta.url)")
    expect(main).toContain("tsImport('./browser/browserSystem.ts', import.meta.url)")
    expect(main).toContain("mainWindow.webContents.send('desktop:runtime-event', event)")
    expect(runtimeHost).toContain("from '@turboflux/agent-core/workbench'")
    expect(runtimeHost).toContain('buildWorkPackCatalog({')
    expect(runtimeHost).toContain('await runtime.installPlugin(temporaryDirectory, approvedPermissions)')
    expect(runtimeHost).not.toContain('runtime.installMarketplacePlugin(entry.backend.marketplaceId')
    expect(runtimeHost).not.toMatch(/from ['"]\.\.?\/[^'"]*(?:application|core|shared)\//)
    expect(runtimeHost).toContain('new WorkbenchRuntime({')
    expect(runtimeHost).toContain('connectMcp: true')
    expect(runtimeHost).toContain('registerSystemPlugins: this.registerSystemPlugins')
    expect(runtimeHost).toContain('await runtime.initializePlatform()')
    expect(runtimeHost).toContain("const DESKTOP_REMOVED_TOOLS = ['web_search', 'web_fetch']")
    expect(runtimeHost).toContain('runtime.runtime.engine.setDisabledTools')
    expect(runtimeHost).toContain("this.scheduleTaskTitleUpdate(snapshot.conversation.id, promptCount, result.status === 'started' ? titleApplyGate : undefined)")
    expect(runtimeHost).toContain("runtime.renameConversation(conversationId, title, 'generated')")
    expect(runtimeHost).toContain('runtimeTransitionBlocker(runtime.getSnapshot(), options)')
    expect(runtimeHost).toContain('const externalBlocker = this.externalTransitionBlocker?.()')
    expect(runtimeHost).toContain('this.runtime !== runtime || this.runtimeEpoch !== runtimeEpoch')
    expect(runtimeHost).toContain('stopConversation(id: string)')
    expect(runtimeHost).toContain('resumeConversation(id: string)')
    expect(runtimeHost).toContain('const activeWorkspacePath = resolve(this.requireRuntime().getSnapshot().workspace.path)')
    expect(main).toContain('reconcileConversationSystems(snapshot)')
    expect(main).toContain('reconcileConversationSystems(runtimeHost.getSnapshot())')
    expect(main).toContain('runtimeHostGeneration += 1')
    expect(main).toContain('await runtimeHostResetPromise')
    expect(main).toContain('host.stopConversation(runtime.conversationId)')
    expect(main).toContain('const conversationId = activeConversationId || host.getSnapshot().conversation.id')
    expect(main).toContain('const paused = host.pauseConversation(conversationId)')
    expect(runtimeHost).toContain("const paused = snapshot.runtime.status === 'paused'")
    expect(runtimeHost).toContain('runtime.submitPrompt(prompt, attachments, capabilities, { forceQueue: paused })')
    expect(main).toContain("await realpath(resolve(host.getSnapshot().workspace.path, '.turboflux', 'attachments'))")
    expect(main).toMatch(/desktop:browser-get-state[\s\S]*?await getRuntimeHost\(\)[\s\S]*?requireBrowserSystem\(\)\.getSnapshot\(\)/)
    expect(runtimeHost).not.toContain('if (promptCount === 1) this.scheduleTaskTitleUpdate')
    expect(runtimeHost).toContain("name: specified ? snapshot.workspace.name : '未指定工作区'")
  })

  it('registers browser artifacts and isolates plugin code', () => {
    const main = readDesktopFile('main.mjs')
    const coreManifest = JSON.parse(readFileSync(new URL('../../node_modules/@turboflux/agent-core/package.json', import.meta.url), 'utf8'))

    expect(main).toContain("event?.type === 'artifact-ready' && event.path")
    expect(main).toContain("const source = event.kind === 'download' ? 'browser-download' : 'browser'")
    expect(main).toContain("visualSource: 'computer'")
    expect(main).toContain("console.error('Failed to register computer visual evidence:'")
    expect(coreManifest.exports).toHaveProperty('./workbench')
    expect(coreManifest.exports).toHaveProperty('./extensions')
    expect(coreManifest.exports).not.toHaveProperty('./core/*')
    expect(coreManifest.exports).not.toHaveProperty('./application/*')
  })

  it('guides macOS Computer permissions through native dialogs and focus refresh', () => {
    const main = readDesktopFile('main.mjs')

    expect(main).toContain('const COMPUTER_PERMISSION_GUIDES = {')
    expect(main).toContain('dialog.showMessageBox(mainWindow')
    expect(main).toContain("buttons: ['继续申请', '取消']")
    expect(main).toContain("buttons: ['打开系统设置', '取消']")
    expect(main).toContain("if (kind === 'screen-recording') return app.isPackaged ? 'TurboFlux' : 'Electron'")
    expect(main).toContain("'TurboFlux Computer Helper（系统也可能显示 TurboFluxComputerHelper）'")
    expect(main).toContain("outcome: 'cancelled'")
    expect(main).toContain("outcome: computerPermissionStatus(snapshot, kind).state === 'granted' ? 'granted' : 'needs-settings'")
    expect(main).toContain("mainWindow.on('focus'")
    expect(main).toContain('computerSystem?.refresh()')
  })

  it('puts Computer approvals and task controls on the non-activating floating panel', () => {
    const main = readDesktopFile('main.mjs')
    const overlay = readDesktopFile('computer/computerActivityOverlay.ts')
    const preload = readDesktopFile('computer/computerActivityOverlayPreload.cjs')
    const builder = readDesktopFile('electron-builder.yml')
    const system = readDesktopFile('computer/computerSystem.ts')

    expect(overlay).toContain('setFocusable(false)')
    expect(overlay).toContain('setIgnoreMouseEvents(false)')
    expect(overlay).toContain('仅这次允许')
    expect(overlay).toContain('本任务自动')
    expect(overlay).toContain('id="take-control"')
    expect(overlay).toContain('id="resume-control"')
    expect(overlay).toContain('id="stop-control"')
    expect(preload).toContain("ipcRenderer.invoke('desktop:computer-overlay-action'")
    expect(builder).toContain('computer/**/*.cjs')
    expect(main).toContain("electronIpcMain.handle('desktop:computer-overlay-action'")
    expect(main).toContain('computerActivityOverlay?.ownsWebContents(event.sender)')
    expect(main).toContain("COMPUTER_APPROVAL_RESTORE_TOOLS.has(request.toolName || '')")
    expect(main).toContain('restoreObservedTargetAfterApproval()')
    expect(system).toContain('async restoreObservedTargetAfterApproval()')
  })

  it('isolates remote browser content in a main-process system plugin', () => {
    const browser = readDesktopFile('browser/browserSystem.ts')
    const browserSession = readDesktopFile('browser/browserSession.ts')
    const browserCapture = readDesktopFile('browser/browserCapture.ts')
    const browserTools = readDesktopFile('browser/browserTools.ts')

    expect(browserSession).toContain("const BROWSER_PARTITION_PREFIX = 'persist:turboflux-browser-v2'")
    expect(browser).toContain('this.partition = browserPartition(conversationId)')
    expect(browser).toContain('const browserSession = session.fromPartition(this.partition')
    expect(browser).toContain('registerBrowserSession(browserSession')
    expect(browser).toContain('new WebContentsView({')
    expect(browser).toContain('nodeIntegration: false')
    expect(browser).toContain('contextIsolation: true')
    expect(browser).toContain('sandbox: true')
    expect(browser).toContain('webSecurity: true')
    expect(browserSession).toContain('setPermissionRequestHandler')
    expect(browser).not.toContain("requiresSelection: true")
    expect(browser).toContain("Password fields must be filled manually")
    expect(browser).toContain('mkdirSync(directory, { recursive: true })')
    expect(browserTools).toContain("name: 'diagnostics'")
    expect(browserTools).toContain("name: 'assert'")
    expect(browserTools).toContain("name: 'click_at'")
    expect(browserTools).toContain("name: 'open'")
    expect(browserTools).toContain("name: 'tabs'")
    expect(browserTools).toContain("name: 'close'")
    expect(browserTools).toContain("tab_id: { type: 'string' }")
    expect(browser).toContain('redactDiagnosticUrl')
    expect(browser).toContain('sendInputEvent')
    expect(browser).toContain('MAX_BROWSER_DOWNLOAD_BYTES')
    expect(browser).toContain('this.requireCurrentRef(tab, ref)')
    expect(browser).toContain('for (const download of this.activeDownloads) download.cancel()')
    expect(browserCapture).toContain("debuggerApi.sendCommand('Page.captureScreenshot'")
    expect(browserCapture).not.toContain('capturePage()')
  })

  it('fails closed when the packaged macOS computer helper is unavailable', () => {
    const computer = readDesktopFile('computer/macosComputerDriver.ts')

    expect(computer).toContain('if (app.isPackaged)')
    expect(computer).toContain('signed helper is missing or invalid')
    expect(computer).toContain("access(path, constants.X_OK)")
    expect(computer).toContain('if (signal?.aborted) throw computerOperationAbortError()')
    expect(computer).toContain("error.name = 'AbortError'")
  })

  it('revalidates observed application and window ownership inside native input commands', () => {
    const main = readDesktopFile('main.mjs')
    const system = readDesktopFile('computer/computerSystem.ts')
    const driver = readDesktopFile('computer/macosComputerDriver.ts')
    const helper = readDesktopFile('computer/native/TurboFluxComputerHelper.swift')

    expect(system).toContain('async finishTask(): Promise<void>')
    expect(main).toContain('computerSystem.finishTask()')
    expect(driver).toContain('expectedTarget: ComputerExpectedTarget')
    expect(driver).toContain('expectedTarget: options.expectedTarget')
    expect(helper).toContain('private func validateExpectedTarget')
    expect(helper).toContain('private func validatePointerTarget')
    expect(helper).toContain('private func ensureInputTrusted()')
    expect(helper).toContain('CGSSessionScreenIsLocked')
    expect(helper).toContain('guard CGPreflightPostEventAccess() else { fail("Input control permission is required") }')
    expect(helper).toContain('A complete expected pointer target is required')
    expect(helper).toContain('The target window moved, closed, or changed; observe again')
    expect(helper).toContain('requireFrontmost: false')
    expect(helper).toContain('validatePointerTarget(point: point, expected: request["expectedTarget"] as? JSON)')
    expect(helper).toContain('validatePointerTargets(points: [points[0], points.last!], expected: request["expectedTarget"] as? JSON)')
    expect(helper).toContain('The keyboard target does not match the observed application')
    expect(helper).toContain('The text target does not match the observed application')
    expect(helper.match(/validateExpectedTarget\(request\["expectedTarget"\] as\? JSON\)/g)).toHaveLength(2)
  })

  it('keeps desktop background work in a general-purpose mental model', () => {
    const runtimeHost = readDesktopFile('runtimeHost.ts')
    const experience = readDesktopFile('productExperience.ts')

    expect(runtimeHost).toContain('surfaceSystemPrompt: DESKTOP_EXPERIENCE_SYSTEM_PROMPT')
    expect(runtimeHost).toContain("conversationPrefix: 'desktop'")
    expect(experience).toContain('present background execution through user intent and outcomes rather than terminal mechanics')
    expect(experience).toContain('Do not repeat raw commands')
    expect(experience).toContain('Describe services as local previews or local services')
    expect(experience).toContain('Installed official capability packs are always available to the Agent')
    expect(experience).toContain('they never unlock, hide, or disable tools')
    expect(experience).not.toContain('built-in Browser')
    expect(experience).not.toContain('visual_observe')
    expect(experience).toContain('Treat substantial final responses as finished work products')
    expect(experience).toContain('separate verified findings, evidence or source links, uncertainties, and recommended next actions')
    expect(experience).toContain('concise progress narration only at meaningful stage boundaries')
  })

  it('keeps development on a deterministic Vite port with main-process watching', () => {
    const vite = readDesktopFile('vite.config.mjs')
    const devScript = readFileSync(new URL('../../scripts/desktop-dev.mjs', import.meta.url), 'utf8')

    expect(vite).toContain('port: 5174')
    expect(vite).toContain('strictPort: true')
    expect(devScript).toContain('const closeWatchers = [mainEntry, preloadEntry, runtimeHostEntry]')
    expect(devScript).toContain("const publicRepositoryRoot = repositoryRoot")
    expect(devScript).toContain("for (const directory of ['application', 'core', 'kernel', 'platform', 'shared', 'state', 'tools'])")
    expect(devScript).toContain("for (const directory of ['browser', 'computer', 'systems'])")
    expect(devScript).toContain('buildSharedCore()')
    expect(devScript).toContain('rebuildCoreAndRestart')
    expect(devScript).toContain('watch(file, restartElectron)')
    expect(devScript).toContain('const expectedElectronExits = new WeakSet()')
    expect(devScript).toContain('expectedElectronExits.add(electronProcess)')
  })
})
