const { contextBridge, ipcRenderer, webUtils } = require('electron')

contextBridge.exposeInMainWorld('turbofluxDesktop', {
  getSnapshot: () => ipcRenderer.invoke('desktop:get-snapshot'),
  getSettings: forceModels => ipcRenderer.invoke('desktop:get-settings', forceModels),
  saveSettings: update => ipcRenderer.invoke('desktop:save-settings', update),
  listCommands: () => ipcRenderer.invoke('desktop:list-commands'),
  executeCommand: command => ipcRenderer.invoke('desktop:execute-command', command),
  submitPrompt: (prompt, attachments, capabilities) => ipcRenderer.invoke('desktop:submit-prompt', prompt, attachments, capabilities),
  resendFromTurn: (turnId, prompt) => ipcRenderer.invoke('desktop:resend-from-turn', turnId, prompt),
  recordDraft: draft => ipcRenderer.invoke('desktop:record-draft', draft),
  openExternal: url => ipcRenderer.invoke('desktop:open-external', url),
  browserGetState: () => ipcRenderer.invoke('desktop:browser-get-state'),
  browserShow: () => ipcRenderer.invoke('desktop:browser-show'),
  browserHide: () => ipcRenderer.invoke('desktop:browser-hide'),
  browserNewTab: url => ipcRenderer.invoke('desktop:browser-new-tab', url),
  browserActivateTab: tabId => ipcRenderer.invoke('desktop:browser-activate-tab', tabId),
  browserCloseTab: tabId => ipcRenderer.invoke('desktop:browser-close-tab', tabId),
  browserNavigate: (url, tabId) => ipcRenderer.invoke('desktop:browser-navigate', url, tabId),
  browserBack: tabId => ipcRenderer.invoke('desktop:browser-back', tabId),
  browserForward: tabId => ipcRenderer.invoke('desktop:browser-forward', tabId),
  browserReload: tabId => ipcRenderer.invoke('desktop:browser-reload', tabId),
  browserSetBounds: bounds => ipcRenderer.invoke('desktop:browser-set-bounds', bounds),
  computerGetState: () => ipcRenderer.invoke('desktop:computer-get-state'),
  computerRefresh: () => ipcRenderer.invoke('desktop:computer-refresh'),
  computerRequestPermission: kind => ipcRenderer.invoke('desktop:computer-request-permission', kind),
  computerOpenPermissionSettings: kind => ipcRenderer.invoke('desktop:computer-open-permission-settings', kind),
  computerRelaunch: () => ipcRenderer.invoke('desktop:computer-relaunch'),
  computerTakeControl: () => ipcRenderer.invoke('desktop:computer-take-control'),
  computerResumeControl: () => ipcRenderer.invoke('desktop:computer-resume-control'),
  computerEmergencyStop: () => ipcRenderer.invoke('desktop:computer-emergency-stop'),
  stop: () => ipcRenderer.invoke('desktop:stop'),
  pause: () => ipcRenderer.invoke('desktop:pause'),
  resume: () => ipcRenderer.invoke('desktop:resume'),
  controlWorkStep: (taskId, action) => ipcRenderer.invoke('desktop:control-work-step', taskId, action),
  resolveRequest: (requestId, response) => ipcRenderer.invoke('desktop:resolve-request', requestId, response),
  setMode: mode => ipcRenderer.invoke('desktop:set-mode', mode),
  newConversation: () => ipcRenderer.invoke('desktop:new-conversation'),
  newConversationInProject: id => ipcRenderer.invoke('desktop:new-project-conversation', id),
  switchConversation: id => ipcRenderer.invoke('desktop:switch-conversation', id),
  deleteConversation: id => ipcRenderer.invoke('desktop:delete-conversation', id),
  renameConversation: (id, title) => ipcRenderer.invoke('desktop:rename-conversation', id, title),
  readSubAgent: (taskId, offset, limit) => ipcRenderer.invoke('desktop:read-subagent', taskId, offset, limit),
  stopSubAgent: taskId => ipcRenderer.invoke('desktop:stop-subagent', taskId),
  retrySubAgent: taskId => ipcRenderer.invoke('desktop:retry-subagent', taskId),
  gitStage: paths => ipcRenderer.invoke('desktop:git-stage', paths),
  gitUnstage: paths => ipcRenderer.invoke('desktop:git-unstage', paths),
  gitCommit: (message, paths) => ipcRenderer.invoke('desktop:git-commit', message, paths),
  gitCreateBranch: (name, startPoint) => ipcRenderer.invoke('desktop:git-create-branch', name, startPoint),
  gitSwitchBranch: name => ipcRenderer.invoke('desktop:git-switch-branch', name),
  gitRestore: (paths, source) => ipcRenderer.invoke('desktop:git-restore', paths, source),
  gitPush: (remote, branch, setUpstream) => ipcRenderer.invoke('desktop:git-push', remote, branch, setUpstream),
  gitDiff: (path, scope) => ipcRenderer.invoke('desktop:git-diff', path, scope),
  listProjects: () => ipcRenderer.invoke('desktop:list-projects'),
  addProject: () => ipcRenderer.invoke('desktop:add-project'),
  updateProject: (id, patch) => ipcRenderer.invoke('desktop:update-project', id, patch),
  removeProject: id => ipcRenderer.invoke('desktop:remove-project', id),
  openProject: id => ipcRenderer.invoke('desktop:open-project', id),
  revealProject: id => ipcRenderer.invoke('desktop:reveal-project', id),
  listAutomations: () => ipcRenderer.invoke('desktop:list-automations'),
  createAutomation: input => ipcRenderer.invoke('desktop:create-automation', input),
  updateAutomation: (id, patch) => ipcRenderer.invoke('desktop:update-automation', id, patch),
  removeAutomation: id => ipcRenderer.invoke('desktop:remove-automation', id),
  duplicateAutomation: id => ipcRenderer.invoke('desktop:duplicate-automation', id),
  runAutomation: id => ipcRenderer.invoke('desktop:run-automation', id),
  retryAutomationRun: (id, runId) => ipcRenderer.invoke('desktop:retry-automation-run', id, runId),
  cancelAutomationRun: id => ipcRenderer.invoke('desktop:cancel-automation-run', id),
  listArtifacts: () => ipcRenderer.invoke('desktop:list-artifacts'),
  previewArtifact: (id, purpose = 'full') => ipcRenderer.invoke('desktop:preview-artifact', id, purpose),
  previewImageAttachment: (path, purpose = 'full') => ipcRenderer.invoke('desktop:preview-image-attachment', path, purpose),
  openArtifact: id => ipcRenderer.invoke('desktop:open-artifact', id),
  revealArtifact: id => ipcRenderer.invoke('desktop:reveal-artifact', id),
  exportArtifact: id => ipcRenderer.invoke('desktop:export-artifact', id),
  exportImageAttachment: path => ipcRenderer.invoke('desktop:export-image-attachment', path),
  removeArtifact: id => ipcRenderer.invoke('desktop:remove-artifact', id),
  listPlugins: () => ipcRenderer.invoke('desktop:list-plugins'),
  installPlugin: () => ipcRenderer.invoke('desktop:install-plugin'),
  installMarketplacePlugin: id => ipcRenderer.invoke('desktop:install-marketplace-plugin', id),
  setPluginEnabled: (id, enabled) => ipcRenderer.invoke('desktop:set-plugin-enabled', id, enabled),
  uninstallPlugin: id => ipcRenderer.invoke('desktop:uninstall-plugin', id),
  retryPersistence: () => ipcRenderer.invoke('desktop:retry-persistence'),
  exportRecovery: () => ipcRenderer.invoke('desktop:export-recovery'),
  activateSkill: skillId => ipcRenderer.invoke('desktop:activate-skill', skillId),
  deactivateSkill: () => ipcRenderer.invoke('desktop:deactivate-skill'),
  reloadSkills: () => ipcRenderer.invoke('desktop:reload-skills'),
  listSkillMarketplace: () => ipcRenderer.invoke('desktop:list-skill-marketplace'),
  installMarketplaceSkill: (marketplaceId, allowOverwrite) => ipcRenderer.invoke('desktop:install-marketplace-skill', marketplaceId, allowOverwrite),
  cancelMarketplaceSkillInstall: marketplaceId => ipcRenderer.invoke('desktop:cancel-marketplace-skill-install', marketplaceId),
  uninstallMarketplaceSkill: marketplaceId => ipcRenderer.invoke('desktop:uninstall-marketplace-skill', marketplaceId),
  listWorkPacks: () => ipcRenderer.invoke('desktop:list-work-packs'),
  installWorkPack: (workPackId, allowOverwrite) => ipcRenderer.invoke('desktop:install-work-pack', workPackId, allowOverwrite),
  cancelWorkPackInstall: workPackId => ipcRenderer.invoke('desktop:cancel-work-pack-install', workPackId),
  setWorkPackEnabled: (workPackId, enabled) => ipcRenderer.invoke('desktop:set-work-pack-enabled', workPackId, enabled),
  uninstallWorkPack: workPackId => ipcRenderer.invoke('desktop:uninstall-work-pack', workPackId),
  reconnectMcp: name => ipcRenderer.invoke('desktop:reconnect-mcp', name),
  acknowledgeNotification: id => ipcRenderer.invoke('desktop:acknowledge-notification', id),
  listMemories: (filters, forceReload) => ipcRenderer.invoke('desktop:list-memories', filters, forceReload),
  rememberMemory: input => ipcRenderer.invoke('desktop:remember-memory', input),
  updateMemory: (id, update) => ipcRenderer.invoke('desktop:update-memory', id, update),
  forgetMemory: (id, reason) => ipcRenderer.invoke('desktop:forget-memory', id, reason),
  chooseFiles: () => ipcRenderer.invoke('desktop:choose-files'),
  importFiles: paths => ipcRenderer.invoke('desktop:import-files', paths),
  importClipboardImage: (base64, mime, filename) => ipcRenderer.invoke('desktop:import-clipboard-image', base64, mime, filename),
  chooseSkill: () => ipcRenderer.invoke('desktop:choose-skill'),
  pathForFile: file => webUtils.getPathForFile(file),
  chooseWorkspace: () => ipcRenderer.invoke('desktop:choose-workspace'),
  onRuntimeEvent: listener => {
    const handler = (_event, payload) => listener(payload)
    ipcRenderer.on('desktop:runtime-event', handler)
  },
  onBrowserEvent: listener => {
    const handler = (_event, payload) => listener(payload)
    ipcRenderer.on('desktop:browser-event', handler)
  },
  onComputerEvent: listener => {
    const handler = (_event, payload) => listener(payload)
    ipcRenderer.on('desktop:computer-event', handler)
  },
})
